### ISSUE TITLE
Debug and Error handling related issues

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-context#67]
Debug:
- [ ] Replace ctx.debug with ctx.set({ debug: }) https://github.com/pex-gl/pex-context/issues/44
- [ ] Use webgl-debug in debug mode https://github.com/pex-gl/pex-context/issues/40
- [ ] debugCommands list is not cleared https://github.com/pex-gl/pex-context/issues/39
- [ ] Get rid of GraphViz dot code generation https://github.com/pex-gl/pex-context/issues/28

Error:
- [ ] Runtime error handling  https://github.com/pex-gl/pex-context/issues/54
- [ ] Verify pipeline parameters #20
